#!/bin/bash
#
# chkconfig: 2345 56 26
set -u -e -E -o pipefail


CONFIGFILE=/etc/sysconfig/yadtbroadcast-server

[[ -r $CONFIGFILE ]] && source $CONFIGFILE

[[ -z $uid ]] && {
        echo "No uid configured in $CONFIGFILE" >&2
        exit 1
}

CMD=${1:?no command given, aborting}

PROG=/usr/bin/yadtbroadcast-server.py
NAME=$(basename $PROG .py)
PID=$(pidof python | xargs ps -o pid=,cmd= | grep $PROG | sed s/^\\s*// | cut -d" " -f1 || :)
NOLOG=/tmp/$NAME.nolog



case "$CMD" in
    start)
        if [[ -z $PID ]]; then
            echo "starting $PROG"
            runuser -l $uid -c $PROG < /dev/null > $NOLOG 2>&1 &
        else
            echo "already running"
        fi
        exit 0
        ;;
    stop)
        if [[ -n $PID ]]; then
            echo "stopping $PROG"
            runuser -l $uid -c "kill $PID"
            while kill -0 "$PID" > /dev/null 2>&1; do
                sleep 0.5
            done
            echo "Shutdown successful"
            # need to do this with a timeout, but so far there have never been problems
        else
            echo "already stopped"
        fi
        exit 0
        ;;
    status)
        echo "pid of $NAME service: $PID"
        [[ -n $PID ]]
        exit
        ;;
    *)
        ;;
esac

